package programacion.dam.tarea9.ventanas;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JList;
import javax.swing.SwingUtilities;
import programacion.dam.tarea9.beans.CuentaBancaria;
import programacion.dam.tarea9.util.Util;

/**
 *
 * @author Roach
 */
public class Principal extends javax.swing.JFrame {

    // Atributos
    DatosCuenta ventanaDatosCuenta;
    AltaCuentas ventanaAltaCuentas;
    ListadoCuentas ventanaListadoCuentas;
    Mix ventanaVarios;
    
//    JList<String> listaCombo;
    DefaultComboBoxModel<String> modeloLista;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public Principal() {
//        listaCombo = new JList<>();
        modeloLista = new DefaultComboBoxModel<>();
        
        // Recargamos la lista de cuentas seleccionables
        this.cargarListaCCC();
        
        initComponents();
        ventanaDatosCuenta = new DatosCuenta();
        ventanaAltaCuentas = new AltaCuentas();
        ventanaListadoCuentas = new ListadoCuentas();
        ventanaVarios = new Mix();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBotones = new javax.swing.JPanel();
        bCuentaNueva = new javax.swing.JButton();
        bCuentasDisponibles = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbListaCuentas = new javax.swing.JComboBox<>();
        bDatosCuenta = new javax.swing.JButton();
        bIngresar = new javax.swing.JButton();
        bRetirar = new javax.swing.JButton();
        bConsultarSaldo = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jtAccionesPrincipales = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBotones.setToolTipText("");

        bCuentaNueva.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bCuentaNueva.setText("Nueva Cuenta");
        bCuentaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCuentaNuevaActionPerformed(evt);
            }
        });

        bCuentasDisponibles.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bCuentasDisponibles.setText("Cuentas Disponibles");
        bCuentasDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCuentasDisponiblesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Cuenta");

        cbListaCuentas.setModel(this.modeloLista
        );
        cbListaCuentas.setSelectedIndex(0);
        cbListaCuentas.setToolTipText("");
        cbListaCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbListaCuentasActionPerformed(evt);
            }
        });

        bDatosCuenta.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bDatosCuenta.setText("Datos de la Cuenta");
        bDatosCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDatosCuentaActionPerformed(evt);
            }
        });

        bIngresar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bIngresar.setText("Ingresar");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });

        bRetirar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bRetirar.setText("Retirar");
        bRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetirarActionPerformed(evt);
            }
        });

        bConsultarSaldo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bConsultarSaldo.setText("Consultar Saldo");
        bConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarSaldoActionPerformed(evt);
            }
        });

        bSalir.setBackground(new java.awt.Color(204, 204, 0));
        bSalir.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        jSeparator1.setToolTipText("Trabajar con Cuenta");

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(bSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bConsultarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDatosCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbListaCuentas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCuentaNueva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCuentasDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCuentaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCuentasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbListaCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(bDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setText("Crear icono tipo bancario");

        jtAccionesPrincipales.setRollover(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addComponent(jtAccionesPrincipales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtAccionesPrincipales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jtAccionesPrincipales.getAccessibleContext().setAccessibleParent(jPanelBotones);

        pack();
    }// </editor-fold>//GEN-END:initComponents

// ******************************************* Acciones Botones *************************************************
    
    /**
     * Acción para consultar el saldo de una cuenta seleccionada.
     * @param evt 
     */
    private void bConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarSaldoActionPerformed
        // limpiamos el panel
        jtAccionesPrincipales.removeAll();
        
        jtAccionesPrincipales.add(ventanaVarios.Mix(Util.OPERACION_SALDO, cbListaCuentas.getSelectedItem().toString()));
        
        // Cambiamos el aspecto del panel auxiliar y pintamos la vista de Ingresar en cuenta.
        SwingUtilities.updateComponentTreeUI(this); 
        
        
    }//GEN-LAST:event_bConsultarSaldoActionPerformed

    /**
     * Acción para crear una nueva cuenta
     * @param evt 
     */
    private void bCuentaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCuentaNuevaActionPerformed
        // limpiamos el panel
        jtAccionesPrincipales.removeAll();
        
        // Crear Codigo
        
    }//GEN-LAST:event_bCuentaNuevaActionPerformed

    /**
     * Acción para ver las cuentas disponibles (ya creadas)
     * @param evt 
     */
    private void bCuentasDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCuentasDisponiblesActionPerformed
        // limpiamos el panel
        jtAccionesPrincipales.removeAll();

        // Crear Codigo
        
    }//GEN-LAST:event_bCuentasDisponiblesActionPerformed

    /**
     * Lista de cuentas (desplegable)
     * @param evt 
     */
    private void cbListaCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbListaCuentasActionPerformed
        // limpiamos el panel
        jtAccionesPrincipales.removeAll();

        // Crear Codigo
        
    }//GEN-LAST:event_cbListaCuentasActionPerformed

    /**
     * Acción para ver los datos de una cuenta seleccionada.
     * @param evt 
     */
    private void bDatosCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDatosCuentaActionPerformed
        // limpiamos el panel
        jtAccionesPrincipales.removeAll();

        // Crear Codigo
        
    }//GEN-LAST:event_bDatosCuentaActionPerformed

    /**
     * Acción para ingresar dinero en una cuenta seleccionada.
     * @param evt 
     */
    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed
        // limpiamos el panel
        jtAccionesPrincipales.removeAll();

        jtAccionesPrincipales.add(ventanaVarios.Mix(Util.OPERACION_INGRESAR, cbListaCuentas.getSelectedItem().toString()));
        
        // Cambiamos el aspecto del panel auxiliar y pintamos la vista de Ingresar en cuenta.
        SwingUtilities.updateComponentTreeUI(this);        
    }//GEN-LAST:event_bIngresarActionPerformed

    /**
     * Acción para retirar dinero en una cuenta seleccionada.
     * @param evt 
     */
    private void bRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetirarActionPerformed
        // limpiamos el panel
        jtAccionesPrincipales.removeAll();

        jtAccionesPrincipales.add(ventanaVarios.Mix(Util.OPERACION_RETIRAR, cbListaCuentas.getSelectedItem().toString()));
        
        // Cambiamos el aspecto del panel auxiliar y pintamos la vista de Ingresar en cuenta.
        SwingUtilities.updateComponentTreeUI(this);  
    }//GEN-LAST:event_bRetirarActionPerformed

    /**
     * Acción para salir de la aplicación.
     * @param evt 
     */
    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    // ***************************************************************************************************
// ************************************ Utilidades de la Clase ***************************************
// ***************************************************************************************************
    
    /**
     * Método que carga los articulos que se encuentran en la lista temporal,
     * y recoge los datos mas importantes para cargarlos en la tabla.
     */
    private void cargarListaCCC(){
        // Liampiamos la lista al cargar nuevas cuentas bancarias, para evitar duplicidades.
        modeloLista.removeAllElements();
        
        ArrayList<CuentaBancaria> listaCuentas = Util.listaCuentasBancarias;
        
        for(CuentaBancaria cuenta : listaCuentas){
            // Añadimos a la tabla los datos de la cuenta actual.
            modeloLista.addElement(cuenta.getCcc());
        }
    }
// **************************************************************************************************************
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConsultarSaldo;
    private javax.swing.JButton bCuentaNueva;
    private javax.swing.JButton bCuentasDisponibles;
    private javax.swing.JButton bDatosCuenta;
    private javax.swing.JButton bIngresar;
    private javax.swing.JButton bRetirar;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<String> cbListaCuentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar jtAccionesPrincipales;
    // End of variables declaration//GEN-END:variables
}
